# docker-compose.yml

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=perry101
      # Changed this to a more descriptive name
      - POSTGRES_DB=fastapi_db 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      # Corrected the user and database to match the environment variables
      test: ["CMD-SHELL", "pg_isready -U patrick -d fastapi_db"] 
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi_assistant:
    build: .
    container_name: fastapi_assistant
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Corrected the database name to match what's being created
      - DATABASE_URL=postgresql://patrick:perry101@db:5432/fastapi_db 
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
