version: '3.8'

services:
  postgres_db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=perry101
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_assistant:
    build: .
    container_name: fastapi_assistant
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=perry101
    depends_on:
      - postgres_db

volumes:
  postgres_data:
